#---------------------------------------------------------------------
#NSE API
#---------------------------------------------------------------------

Login = "https://uat-ipo.nseindia.com/eipo/v1/login"
ChangePassword = "https://uat-ipo.nseindia.com/v1/changePassword"
Master = "https://uat-ipo.nseindia.com/eipo/v1/ipomaster"
SgbMaster = "https://uat-ipo.nseindia.com/eipo/v1/sgbmaster"
#SgbMaster = "https://eipo.nseindia.com/eipo/v1/sgbmaster"
NseSgbOrder = "https://uat-ipo.nseindia.com/eipo/v1/sgb/add"
FetchSgbTranscation = "https://uat-ipo.nseindia.com/eipo/v1/sgb/"
Transcation = "https://uat-ipo.nseindia.com/eipo/v1//transactions/addbulk"
Apply = "http://localhost:29091/applyipo"

#Login = "https://eipo.nseindia.com/eipo/v1/login"
#ChangePassword = "https://eipo.nseindia.com/v1/changePassword"
#Master = "https://eipo.nseindia.com/eipo/v1/ipomaster"
#Transcation = "https://eipo.nseindia.com/eipo/v1//transactions/addbulk"
#Apply = "http://localhost:29091/applyipo"

#---------------------------------------------------------------------
#BSE API
#---------------------------------------------------------------------

BseLogin = "https://uat.bseindia.in/ibbsmsgapi/iBBSWebBroadcastApi.svc/v1/login"
BseSgbMaster = "https://uat.bseindia.in/ibbsmsgapi/iBBSWebBroadcastApi.svc/v1/sgbopenissue"
BseSgbOrder = "https://uat.bseindia.in/ibbssgbapi/sgbapi.svc/v1/sgborder"
BseSgbDownload="https://uat.bseindia.in/ibbssgbapi/sgbapi.svc/v1/sgbdownload"
BsePassword="https://uat.bseindia.in/ibbssgbapi/sgbapi.svc/v1/changepwd"

#BsePassword="https://uat.bseindia.in/ibbsapi/ibbsapiservice.svc/v1/changepwd"

BseIpoMaster = "https://uat.bseindia.in/ibbsmsgapi/iBBSWebBroadcastApi.svc/v1/openissue"
BseIpoCategory = "https://uat.bseindia.in/ibbsmsgapi/iBBSWebBroadcastApi.svc/v1/issuetime"
BseIpoOrder = "https://uat.bseindia.in/ibbsapi/ibbsapiservice.svc/v1/ipoorder"


#---------------------------------------------------------------------
# MarketData API
#---------------------------------------------------------------------
MarketDemand = "https://uat-ipo.nseindia.com/eipo/mktdata/v1/demand/"
MarketCatwise = "https://uat-ipo.nseindia.com/eipo/mktdata/v1/catwise/"
Credential = "MTQ1NzJebGFrc2htYW5hbjpiZXN0QDEyMzQ1Njc="
#Credential = "MTQ1NzJeUkFNOkJlc3RAMTIzNDU2Nzg="

#---------------------------------------------------------------------------------------------------------
#Bse MarketData API
BSEMarketCatwise = "https://uat.bseindia.in/ibbsmsgapi/iBBSWebBroadcastApi.svc/v1/biddata"
BSEMarketDemand = "https://uat.bseindia.in/ibbsmsgapi/iBBSWebBroadcastApi.svc/v1/demandschedule"

#----------------------------------------------------------------------------------------------------------



#------------------------------------------------------------------------
#NSENCB -- Prod
#------------------------------------------------------------------------

#NcbMaster = "https://eipo.nseindia.com/eipo/v1/ncbmaster"
#NseNcbOrder = "https://eipo.nseindia.com/eipo/v1/ncb/add"
#NseNcbTime = "https://eipo.nseindia.com/eipo/v1/ncb/"
#NseNcbFetch = "https://eipo.nseindia.com/eipo/v1/ncb/fetch"

#------------------------------------------------------------------------
#NSENCB -- UIT
#------------------------------------------------------------------------
NcbMaster = "https://uat-ipo.nseindia.com/eipo/v1/ncbmaster"
NseNcbOrder = "https://uat-ipo.nseindia.com/eipo/v1/ncb/add"
NseNcbTime = "https://uat-ipo.nseindia.com/eipo/v1/ncb/"
NseNcbFetch = "https://uat-ipo.nseindia.com/eipo/v1/ncb/fetch"