Account = "AKIA4F42KEYBUUXTJN4W"
Pwd = "BMmcqXw7qNrZqalHdkEbaRiFwvi4WtLs1DoxQ4U4dVaI"
From        = "Flattrade <info-noreply@mailer.flattrade.in>" 
FromRaw     = "info-noreply@mailer.flattrade.in"
FromDspName = "Flattrade"
ReplyTo = "itsupport@flattrade.in"
Url = "email-smtp.ap-south-1.amazonaws.com:587"
Mime = "MIME-version: 1.0;\nContent-Type: text/html; charset=\"UTF-8\";\n\n"
SubscribeUrl ="http://ftunsubscribe.s3-website.ap-south-1.amazonaws.com/?us="
ConfigurationSet="FlatTradeMailer"
# AccountsTeamMail = "pavithra.v@fcsonline.co.in"
AccountsTeamMail = "kavyadharshani.m@fcsonline.co.in"
Subject= "Ipo Offline Scheduler"
# ToEmailId = "pavithra.v@fcsonline.co.in"
ToEmailId = "kavyadharshani.m@fcsonline.co.in"
#ToEmailId = "appsupport@flattrade.in"

#BCC emaild for NOVO
#Bcc_emailId = "novoemails@fortunetradingcorporation.zohodesk.com"
Bcc_emailId = "nitishkumar.a@fcsonline.co.in"


######Alternate way to Get Login Email  For Temperary Purpose
LoginUrl =  "http://192.168.150.21:29091/query/?qc=CLEML&typ=v&qp1="
