"apkversion" = "1.0.0"
"imei" = "162.158.227.122:52214" 
"source" = "API"
"vc" = "FLATTRADE"
"appkey" = "ftcAPIkey10072021QW2"
"url" = "https://web.flattrade.in/NorenWClientSpan/QuickAuthExtrn"




#---------------------------------------------------------------------
#AUTH LOGIN API
#---------------------------------------------------------------------

NovoAuthLogin = "https://authapi.flattrade.in/oauth/authorize"
NovoAuthSecretKey = "MjAyMi43NjRmNzhiZmFhM2Rkc2Y4NGo1YTVhY2ZnNjc4ZGVzZGZkc2Y1NDhjMjM0MzJzZDQ2"

#NovoAuthSecretKey = "2022.764f78bfaa3ddsf84j5a5acfg678desdfdsf548c23432sd46"